### ISSUE TITLE
Восстановление TTL после перезагрузки устройства

### ISSUE THREAD

**Issue by swapii** [YotaTetherTTL/yotatetherttl#1]
Оригинальный запрос:
http://4pda.ru/forum/index.php?showtopic=647126&view=findpost&p=39461894

**Comment by kolyanok** [comment]
Есть у кого-нибудь идеи, как это сделать?

**Comment by swapii** [comment]
Думаю надо подписаться на события загрузки устройства.
При получении этого события запускать тот же механизм, что и на главном экране.
При этом надо запоминать какой способ выбрал пользователь и использовать именно его.

**Comment by kolyanok** [comment]
Сделали...
