### ISSUE TITLE
Проверка ядра на возможность изменения TTL через iptables

### ISSUE THREAD

**Issue by swapii** [YotaTetherTTL/yotatetherttl#12]
Оказывается не все ядра одинаково полезны...
Не во всех доступно изменение TTL исходящих пакетов.
Подробности в статье: http://habrahabr.ru/post/238625/

**Comment by krll-k** [comment]
Почитал, оказалось что ни один из моих аппарато не умеют изменять значение ttl у проходящих с квозь него пакетов

Где найти модуль ядра под свой гаджет, или только компиляцией можно?

**Comment by kolyanok** [comment]
Найти, скорее всего, получится вряд ли. Надо самому пилить...

**Comment by derlaft** [comment]
Fixed by #16
