### ISSUE TITLE
Нотификации об изменении TTL

### ISSUE THREAD

**Issue by swapii** [YotaTetherTTL/yotatetherttl#14]
Тоасты слишком быстро исчезают и невозможно узнать, какое приложение из вывело.
Вместо тоастов необходимо отображать нотификации при загрузке. После применения должна оставаться нотификация о новом значении TTL.

**Comment by LionZXY** [comment]
До сих пор открыт?

**Comment by kolyanok** [comment]
@LionZXY, не сделали же пока

**Comment by LionZXY** [comment]
Т.е. вместо тостов должно быть нотификация с ProgressBar? При клике на неё должны открываться логи там или что-то подобное?

**Comment by kolyanok** [comment]
Да можно и без прогресс бара, в принципе.  Логи можно, если включен дебаг режим, но в принципе и без них нормально бы было. Основная проблема тостов — они быстро исчезают и не всегда успеваешь среагировать. С уведомлениями, думаю, было бы куда удобнее. Особенно в случае автозапуска.

**Comment by derlaft** [comment]
Уже давно сделано

**Comment by derlaft** [comment]
![tmp_3760-screenshot_20170601-1953571409986391](https://cloud.githubusercontent.com/assets/852606/26691017/a8f3228c-470c-11e7-849e-e451f0b841e3.png)

**Comment by LionZXY** [comment]
У меня есть желание помочь проекту. К какому issue лучше притронуться?

**Comment by derlaft** [comment]
Хорошо было бы обновить списки блокировок хостов.

Вернуть лог ошибок.

Так же у меня на почте валяется куча креш-репортов, которые можно разобрать и починить соответствующие ошибки.

**Comment by LionZXY** [comment]
Может настроить краш рапорты на firebase? Как вы к Kotlin относитесь?

**Comment by LionZXY** [comment]
Обновить это по домену извлечь ip?

**Comment by derlaft** [comment]
Обновить - это посмотреть, какие еще домены начала блокировать йота и добавить их в список.

Плюс, сейчас у МТС тоже что-то подобное есть. Нужно посмотреть, отличается ли у них список доменов

Еще в идеях было посмотреть, как они там определяют использование торрентов и заблокировать это тоже, чтобы настройка клиента была не нужна

Насчет багрепортов - лично мне все равно, на какой платформе до них никому нет дела. Нужно смотреть их, а не перекладывать куда-то

**Comment by LionZXY** [comment]
По поводу доменов - нафиг надо. Моторная и не интересная работа. А вот баг репорты можно и выложить куда-то кроме твоей почты :)

**Comment by LionZXY** [comment]
Торрент в определяют если устройство в малый промежуток времени открывает и поддерживает соединение с несколькими IP.
Ещё кстати, была мысль сделать правку пакетов, притворившись VPN (не уверен что это возможно)

**Comment by derlaft** [comment]
>притворившись VPN (не уверен что это возможно)

Что ты об этом понимаешь?

Вообще, я думал над тем, чтобы вместо блокировки хостов и торрентов просто посылать их в vpn. Но кончилось тем, что мне лень.

Креш-репорты выложу, когда буду у нормального интернета

**Comment by derlaft** [comment]
Или напиши свою почту, я просто перешлю всё.

**Comment by kolyanok** [comment]
А зачем определять торрент? За него ведь не блочат, а просто скорость режут именно для торрента. Так что не вижу смысла. И я не думаю, что там только соединение с несколькими IP учитывается при определении. Все же у битторента помимо этого есть и другие узнаваемые черты. Хотя, если включено шифрование по дефолту, определить по ним становится сложнее.

**Comment by LionZXY** [comment]
Например? Какие черты?

**Comment by derlaft** [comment]
Вроде, блокировали как раз. Если нормально настроить торрент-клиент (запретить незашифрованные соединения и etc), то будет только резать скорость.

**Comment by LionZXY** [comment]
> Что ты об этом понимаешь?

Звучит как оскорбление :)
Блокировка хостов через VPN - мысль. Её надо обдумать. Но только если, опять же, будет исчерпывающий стоп-лист/автоматическое добавление туда хоста на основе статистических данных.

**Comment by derlaft** [comment]
Извиняюсь, опечатался. Имел в виду "что ты **под** этим понимаешь?"

**Comment by derlaft** [comment]
>Блокировка хостов через VPN - мысль. Её надо обдумать

А шо там думать? Вместо -j DROP ставишь пакету метку, по метке выбираешь путь пакету и профит

https://habrahabr.ru/post/108690/

**Comment by derlaft** [comment]
Хотя, проблемы могут возникнуть, потому что реализация vpn в ведроиде какая-то стремная. Нужно смотреть, как она там "под капотом" устроена

**Comment by LionZXY** [comment]
Уровень абстракции интерфейса VPN достаточен, чтобы можно было изменять TTL?

**Comment by kolyanok** [comment]
>Вроде, блокировали как раз.

Ну хз. Сколько ни оставлял торрент открытым, подключаясь к йоте — ни разу не было бана. Иногда даже пытался что-то скачать, не приходя в сознание. Потом, когда скачивалось медленно, понимал уже, в чем дело.

>Например? Какие черты?

DHT шлет пакеты без шифрования с заголовками, в которых явно указано, что это DHT.
TCP анонс — тоже самое.
Сам торрент-траффик (ну, то есть, непосредственно скачиваемые и раздаваемые файлы) без шифрования тоже палится очень легко. С шифрованием посложнее, но осуществимо.

**Comment by kolyanok** [comment]
>Уровень абстракции интерфейса VPN достаточен, чтобы можно было изменять TTL?

Не совсем понимаю, зачем на vpn интерфейсе менять TTL.

**Comment by derlaft** [comment]
>Ну хз. Сколько ни оставлял торрент открытым, подключаясь к йоте — ни разу не было бана. Иногда даже пытался что-то скачать, не приходя в сознание. Потом, когда скачивалось медленно, понимал уже, в чем дело.

Все очень отличается от региона к региону. Я ловил синие экраны за забытые торренты.

**Comment by kolyanok** [comment]
>Все очень отличается от региона к региону

Может быть. Я, если что, в основном в Москве пользовался.

**Comment by LionZXY** [comment]
> Не совсем понимаю, зачем на vpn интерфейсе менять TTL.

Например, чтобы можно было менять TTL без рута. Но возможность подобного под сомнением

**Comment by kolyanok** [comment]
Так насколько мне известно, пакеты, уходящие на VPN, потом все равно проходят через интерфейс мобильных данных (ну они как-то же должны покидать устройство). Так что если даже поменять TTL на VPN интерфейсе, то измененный TTL будут видеть только машины на другом конце туннеля, но явно не оборудование йоты, которое к VPN никакого отношения не имеет и через которое трафик идет просто транзитом.
Да и учитывая то, что VPN посредством виртуального интерфейса в андройде как такового нет, я вообще сомневаюсь, что поменять TTL удастся

**Comment by derlaft** [comment]
@LionZXY, не понял, чего ты хочешь от VPN-интерфейса. Если VPN работает на девайсе, то дополнительно никаких ttl менять не нужно.

Зато, есть забавный "баг" в андроиде, который упорно не хотят фиксить: при включенном VPN раздача интернета не работает. Его фикс, кстати, можно было бы и запилить функцией в приложение.

**Comment by LionZXY** [comment]
Я думаю фикс такого бага очень длинная история...

**Comment by derlaft** [comment]
Довольно легко

https://forum.xda-developers.com/general/networking/guide-how-to-wifi-tether-vpn-droidvpn-t2990751

Но вообще, на совсем свежих ведрах может уже и пофиксили, я не проверял
