### ISSUE TITLE
Не работает или я что то не то делаю?

### ISSUE THREAD

**Issue by krll-k** [YotaTetherTTL/yotatetherttl#15]
При включение сети передачи данных с помощью команды пинг отображает 54 ттл, а когда делаю тетинг, то на плашете уже 53. Я правильно понимаю что это приложение нужно запускать там где ттл 54, то есть на телефоне?

**Comment by swapii** [comment]
В приложении 2 способа обхода ограничений.
1. Меняем ТТЛ самого устройства.
2. Меняем ТТЛ всех пакетов, проходящих через точку доступа.
Если рассматривать вариант 1, то нужно "подстраиваться" под то устройство, куда хотим раздать интернет.
Подробности тут: http://4pda.ru/forum/index.php?showtopic=596728

**Comment by kolyanok** [comment]
Приложение можно запускать и на планшете, и на телефоне - как Вам больше удобно. На всех устройствах сразу TTL менять не надо. Это надо сделать на одном из них. В первом случае TTL надо ставить 65, во втором 63.

**Comment by krll-k** [comment]
А TTL надо менять до или после того как запускаешь интерфейс(включаешь передачу данных)? Потому что я пробовал изменить его и так и так, но изменения происходят только для lo. В терминале пишу ping localhost и ping vk.com, для локального то которое установил с помощью TTL master, а у rmnet0 по прежнему 54. Откуда берётся значение 54 кто нибудь может объяснить?

В чем может быть причина?

**Comment by krll-k** [comment]
Может TTL менять на wlan0 интерфейсе?

**Comment by krll-k** [comment]
А можно как нибудь сделать чтоб TTL не изменялся на 1?

**Comment by krll-k** [comment]
Я так понял значение 54 передаёт мне йота?

**Comment by krll-k** [comment]
Почему у меня не получается изменить это 54 на своё?

**Comment by krll-k** [comment]
Или мне его не изменить? То есть его не нужно изменять, просто всем пакетам проходящем через мою точку доступа устанавливать тоже самое значение е 54

**Comment by krll-k** [comment]
Хелп

**Comment by kolyanok** [comment]
На телефоне 63 надо ставить, если система компа UNIX, а если Windows — 127. После этого переключить мобильные данные, а лучше авиарежим.

**Comment by kolyanok** [comment]
Закрываю, так как багом это не является.
