### ISSUE TITLE
iptables в автозапуск

### ISSUE THREAD

**Issue by kolyanok** [YotaTetherTTL/yotatetherttl#19]
Надо сделать автозапуск не только обычной смены TTL, но и iptables.

**Comment by derlaft** [comment]
Кхем, уже сделано.

@kolyanok, @swapii Я тут трудоустроился, поэтому закончить начатое, скорее всего, не смогу. Тем не менее, у меня все эти пару недель на 1+1 и список блокировок, и установка ttl стабильно работает. Короче, осталось только массово протестировать и добавить тот костыль для установки ttl без --ttl-set

**Comment by derlaft** [comment]
Тем не менее, список (который я создал в соседней репе) нужно бы проработать тщательнее

**Comment by kolyanok** [comment]
> Кхем, уже сделано.

Извиняюсь.
Спасибо большое за работу. Я лично тоже занят сейчас, так что не знаю, когда-нибудь, может быть, займусь. Скорее всего летом, сейчас учеба...
