### ISSUE TITLE
Требуется внести изминение в код в связи с изминениями в МТС

### ISSUE THREAD

**Issue by ShapovalovIgor** [YotaTetherTTL/yotatetherttl#28]
Проблема в том, что МТС решили всех обмануть. Они входящие пакеты теперь отправляют с TTL=1. При переходе через раздающее устройство TTL теряет одну единицу и пакет самоуничтожается, т.к. TTL=0 считается ошибочными пакетами. Если начинаешь раздавать официально, т.е. без фиксации TTL, то МТС видит прилетающие пакеты с разным TTL и тут же увеличивает TTL на исходящих от себя пакетах до нормального значения, но и трафик считает.
Команда увеличивает TTL входящих пакетов на 1. Последнюю цифру вроде можно увеличить, если раздача идет на роутер и потом дальше. Но я не проверял.
Это только для МТС.

Требуется добавить строчку в скрипт
`iptables -t mangle -I PREROUTING -j TTL --ttl-inc 1`

**Comment by fuldaros** [comment]
буду смотреть

**Comment by ShapovalovIgor** [comment]
Поправил, но из-за отсутствия доступа к репозиторию залил к себе https://github.com/ShapovalovIgor/TTLMaster

**Comment by fuldaros** [comment]
@ShapovalovIgor исправь орфографические ошибки и можешь делать pull request

**Comment by ShapovalovIgor** [comment]
Доступа все равно нет

```
ERROR: Permission to TTLMaster/TTLMaster.git denied to ShapovalovIgor.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by kolyanok** [comment]
@ShapovalovIgor, так пулл реквест открой здесь, через веб гитхаба. Зайди на страницу своего репозитория, сверху вкладка Pull Requests, дальше Create pull request

**Comment by fuldaros** [comment]
Смерджил сам
@ShapovalovIgor, спасибо за предоставленную информацию и решение
